# Generated by Django 2.0.7 on 2018-07-22 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cats'),
            preserve_default=False,
        ),
    ]
