# Generated by Django 2.0.7 on 2018-07-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_feed', '0002_post_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_path',
            new_name='image',
        ),
    ]
